version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile
    networks:
      - web

  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

networks:
  web:
    name: web
