version: 3
services:
  maria:
    container_name: maria
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: maria
    ports:
      - 3306:3306
    volumes:
      - maria_db:/var/lib/mysql

volumes:
  maria_db: