version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf